    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                    </a>
                </div>
                <div class="panel-body">
                   <form action="<?php echo BASE; ?>cadastro/cadastrar/" class="form-horizontal" method="post">

                      <div class="form-group">
                       <label for="name" class="col-sm-3 control-label">Nome:</label>
                          <div class="col-sm-8">
                             <input type="text" name="name" class="form-control" id="name" placeholder="ex: Lucas Rossi ">
                           </div>
                         </div>

                        <div class="form-group">
                       <label for="email" class="col-sm-3 control-label">E-mail:</label>
                          <div class="col-sm-8">
                             <input type="email" name ="email" class="form-control" id="email" placeholder="ex: seuemail@site.com.br ">
                           </div>
                         </div>

                          <div class="form-group">
                       <label for="username" class="col-sm-3 control-label">Usuário:</label>
                          <div class="col-sm-8">
                             <input type="text" name="username" class="form-control" id="username" placeholder="ex: tandembr ">
                           </div>
                         </div>

                         <div class="form-group">
                       <label for="password" class="col-sm-3 control-label">Senha:</label>
                          <div class="col-sm-8">
                             <input type="password" name="password" class="form-control" id="password" placeholder="ex: sua senha ">
                           </div>
                         </div>

                          <div class="form-group">
                           <div class="col-sm-offset-3 col-sm-10">
                             <button type="submit" class="btn btn-sucess">Cadastrar</button>
                           </div>
                         </div>

                           </form>
                </div>
        </div>
    </div>
 </div>
